
---
- name: Install and start Apache on Amazon Linux
  hosts: amzlinux_clients
  become: yes
  vars_files
    - vars.yml
  tasks:
    - name: Install httpd
      yum:
        name: "{{ apache_amzlinux }}"
        state: present
      notify: Restart apache on amazon_linux

  handlers:
    - name: Restart apache on amazon_linux
      service:
        name: "{{ apache_amzlinux }}"
        state: restarted
        enabled: yes

  

- name: Install and start Apache on Ubuntu
  hosts: ubuntu_clients
  become: yes
  vars_files
    - vars.yml
  tasks:
    - name: Install apache2
      apt:
        name: "{{ apache_ubuntu }}"
        state: present
        update_cache: yes
      notify: Start Apache service on ubuntu

  handlers:
    - name: Start Apache service on ubuntu 
      service:
        name: "{{ apache_ubuntu }} "
        state: started
        enabled: yes


        




    
