AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Static Website Hosting Bucket (Demo for CI/CD)

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket (must be globally unique)

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForWebsite
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

Outputs:
  WebsiteURL:
    Description: S3 Static Website URL
    Value: !GetAtt StaticSiteBucket.WebsiteURL

