AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance lanuched in a default VPC

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      Tags:
        - Key: Name
          Value: Simple-CFN-EC2
