
AWSTemplateFormatVersion: "2010-09-09"
Description: Template A - Create SSH Security Group and export SG ID

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  ExportedSGID:
    Description: Security Group ID
    Value: !Ref SSHSecurityGroup
    Export:
      Name: Dev-SSH-SG-ID
